parameters:
    azatyan.locale.translit.class: Azatyan\ArmenianLocaleBundle\Services\Translit
    azatyan.locale.encoding.class: Azatyan\ArmenianLocaleBundle\Services\Encoding
    azatyan.local.whois.server: "whois.amnic.net"
    azatyan.local.whois.class: Azatyan\ArmenianLocaleBundle\Services\Whois
services:
    azatyan.locale.translit:
        class: %azatyan.locale.translit.class%
        arguments: []
    azatyan.locale.encoding:
        class: %azatyan.locale.encoding.class%
        arguments: []
    azatyan.local.whois:
        class: %azatyan.local.whois.class%
        arguments: [%azatyan.local.whois.server%]
