parameters:
    armenian.locale.whois.server: "whois.amnic.net"
services:
    armenian.locale.translit:
        class: Azatyan\ArmenianLocaleBundle\Services\Translit
        arguments: []
    armenian.locale.encoding:
        class: Azatyan\ArmenianLocaleBundle\Services\Encoding
        arguments: []
    armenian.locale.whois:
        class: Azatyan\ArmenianLocaleBundle\Services\Whois
        arguments: [%armenian.locale.whois.server%]
    armenian.locale.helper:
        class: Azatyan\ArmenianLocaleBundle\Services\Helper
    armenian.locale.date.haykyan:
        class: Azatyan\ArmenianLocaleBundle\Services\HaykyanDate