parameters:
    armcoder.locale.translit.class: ArmCoder\ArmenianLocaleBundle\Services\Translit
    armcoder.locale.encoding.class: ArmCoder\ArmenianLocaleBundle\Services\Encoding

services:
    armcoder.locale.translit:
        class: %armcoder.locale.translit.class%
        arguments: []
    armcoder.locale.encoding:
        class: %armcoder.locale.encoding.class%
        arguments: []
