parameters:
    armenian.locale.translit.class: ArmCoder\ArmenianLocaleBundle\Services\Translit
    armenian.locale.encoding.class: ArmCoder\ArmenianLocaleBundle\Services\Encoding

services:
    armenian.locale.translit:
        class: %armenian.locale.translit.class%
        arguments: []
    armenian.locale.encoding:
        class: %armenian.locale.encoding.class%
        arguments: []
