parameters:
    armcoder.locale.translit.class: ArmCoder\ArmenianLocaleBundle\Services\Translit
    armcoder.locale.encoding.class: ArmCoder\ArmenianLocaleBundle\Services\Encoding
    armcoder.local.whois.server: "whois.amnic.net"
    armcoder.local.whois.class: ArmCoder\ArmenianLocaleBundle\Services\Whois
services:
    armcoder.locale.translit:
        class: %armcoder.locale.translit.class%
        arguments: []
    armcoder.locale.encoding:
        class: %armcoder.locale.encoding.class%
        arguments: []
    armcoder.local.whois:
        class: %armcoder.local.whois.class%
        arguments: [%armcoder.local.whois.server%]
