parameters:
    armenian.locale.translit.class: Azatyan\ArmenianLocaleBundle\Services\Translit
    armenian.locale.encoding.class: Azatyan\ArmenianLocaleBundle\Services\Encoding
    armenian.locale.whois.server: "whois.amnic.net"
    armenian.locale.whois.class: Azatyan\ArmenianLocaleBundle\Services\Whois
    armenian.locale.helper.class: Azatyan\ArmenianLocaleBundle\Services\Helper

services:
    armenian.locale.translit:
        class: %armenian.locale.translit.class%
        arguments: []
    armenian.locale.encoding:
        class: %armenian.locale.encoding.class%
        arguments: []
    armenian.locale.whois:
        class: %armenian.locale.whois.class%
        arguments: [%armenian.locale.whois.server%]
    armenian.locale.helper:
        class: %armenian.locale.helper.class%
